# config.yaml

data:
  input_dir: "colored_oranges"
  target_dir: "target_oranges"

training:
  epochs: 1000
  batch_size: 4
  learning_rate: 0.0001
  min_lr: 0.000001
  scheduler: cosine
  print_freq: 10

early_stopping:
  base_patience: 30
  max_patience: 100

model:
  save_path: "simple_net.pth"
